version: "3.7"
services:
  postfix:
    build: ../..
    restart: always
    environment:
      FORCE_COLOR: "1"
      TZ: Europe/Amsterdam
      # XXX: maso, 2021: read All date from db
      POSTFIX_DB_TYPE: pgsql
      POSTFIX_DB_HOST: db
      POSTFIX_DB_NAME: postgres
      POSTFIX_DB_USER: odoo
      POSTFIX_DB_PASSWORD: odoo
      POSTFIX_mynetworks: 0.0.0.0
    networks:
     - test-net
    ports:
     - '587:587'
    logging:
      driver: local
    volumes:
     - /mnt/postfix/spool:/var/mail
     - /mnt/postfix/spool:/var/spool/mail

  db:
    image: postgres:13
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    networks:
     - test-net
    logging:
      driver: none
  mail:
    image: postfixadmin:3.3.10
    environment:
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_NAME: postgres
      POSTFIXADMIN_DB_PASSWORD: odoo
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_USER: odoo
      POSTFIXADMIN_ENCRYPT: md5
      # Abc123
      POSTFIXADMIN_SETUP_PASSWORD: $$2y$$10$$AXOmkSGMgrnHRfhetJvlV.nj1jAtAA2KUDQv.GptTxpg5OckKAe8y
      POSTFIXADMIN_SMTP_PORT: 587
      POSTFIXADMIN_SMTP_SERVER: postfix
      INBOUND_DEBUGGING: 1
    ports:
     - '8080:80'
    networks:
     - test-net
    logging:
      driver: local

networks:
  test-net:
      